authorName: Renaldi
experimentName: trace
trialConcurrency: 1
maxExecDuration: 1000h
maxTrialNum: 1
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false

tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  gpuIndices: 0
  
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
    
trial:
  command: python universal_attack_nni.py
  codeDir: .
  gpuNum: 0
  
localConfig:
  maxTrialNumPerGpu: 1
  useActiveGpu: true
  gpuIndices: 0
  
  